// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCdQNwDNnf1O700WxBcfjopy6CIhOfMsc',
    appId: '1:1050847711151:web:3061784e4b9a87412ea95a',
    messagingSenderId: '1050847711151',
    projectId: 'tradeupapp-b3d24',
    authDomain: 'tradeupapp-b3d24.firebaseapp.com',
    storageBucket: 'tradeupapp-b3d24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVG53ehEV9wd2zV7RG0gHTcDAgQg24sXQ',
    appId: '1:1050847711151:android:159d2a54181004132ea95a',
    messagingSenderId: '1050847711151',
    projectId: 'tradeupapp-b3d24',
    storageBucket: 'tradeupapp-b3d24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2bulNCSgi-j6dc-bdladyCQ_vrIoQsSA',
    appId: '1:1050847711151:ios:56c64ff84c1a1a762ea95a',
    messagingSenderId: '1050847711151',
    projectId: 'tradeupapp-b3d24',
    storageBucket: 'tradeupapp-b3d24.firebasestorage.app',
    iosBundleId: 'com.example.tradeupapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2bulNCSgi-j6dc-bdladyCQ_vrIoQsSA',
    appId: '1:1050847711151:ios:56c64ff84c1a1a762ea95a',
    messagingSenderId: '1050847711151',
    projectId: 'tradeupapp-b3d24',
    storageBucket: 'tradeupapp-b3d24.firebasestorage.app',
    iosBundleId: 'com.example.tradeupapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCdQNwDNnf1O700WxBcfjopy6CIhOfMsc',
    appId: '1:1050847711151:web:3147a7e3ebf3f0022ea95a',
    messagingSenderId: '1050847711151',
    projectId: 'tradeupapp-b3d24',
    authDomain: 'tradeupapp-b3d24.firebaseapp.com',
    storageBucket: 'tradeupapp-b3d24.firebasestorage.app',
  );
}
